### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by anibalsanchez** [imagekit-developer/embeddable-media-library#6]
Hi,

We are evaluating the service to integrate it into a Spanish newspaper. The writers and editors are used to manage images in
Spanish, and we are used to developing the site and translating everything into Spanish. 

I have checked this repository, but it seems that the widget itself is not open source, and it is downloaded from this URL https://eml.imagekit.io/media-library-widget?redirectTo=media-library-widget&isMediaLibraryWidget=true and https://eml.imagekit.io/dist/js/media-library-widget.js.

Is there a possibility to customize the ImageKit Media Library Widget and translate it? Do you have plans to support other languages?

**Comment by imagekitio** [comment]
This widget opens the ImageKit dashboard in an iframe. I am afraid, at the moment, we only support English and don't have Spanish transformation on the roadmap.
